Создание http-сервера с помощью Express; обработка маршрутов.
htmlacademy-nodejs/1871633-typoteka-3 pull request #7
Opened 2021-11-07 19:57 UTC by linadorasheva

2021-11-08 18:16 UTC, dean992008 requested changes

2021-11-08 18:16 UTC, dean992008 commented on src/express/express.js
> +app.use(`/articles`, articlesRoutes);
Корневые роуты лучше вынести в отдельный роутер модуль по примеру `articles-routes.js` и подключить его  сюда через `app.use(router)`.

2021-11-08 18:16 UTC, dean992008 commented on src/express/routes/articles-routes.js
> +articlesRouter.get(`/category/:id`, (req, res) => res.send(`articles/category/:id`));
Нужно сделать так чтобы если перейти `articles/category/3` то и выдало `articles/category/3`

2021-11-08 18:16 UTC, dean992008 commented on src/service/cli/server.js
> +    const port = Number.parseInt(customPort, 10) || Port.DEFAULT_SERVICE_PORT;
Если передан не коректный порт лучше выдавать ошибку.

2021-12-12 19:04 UTC, linadorasheva commented on src/service/cli/server.js
> +    const port = Number.parseInt(customPort, 10) || Port.DEFAULT_SERVICE_PORT;
Да, но нужно было указать именно дефолтный порт в соответствии со вторым пунктом задания https://up.htmlacademy.ru/nodejs/3/tasks/12 Оставим без изменений?)

2021-12-13 13:19 UTC, dean992008 commented on src/service/cli/server.js
> +    const port = Number.parseInt(customPort, 10) || Port.DEFAULT_SERVICE_PORT;
Я думаю в таком случае достаточно убрать `Port.DEFAULT_SERVICE_PORT` в 49, так будет выглядеть корректно. 
Я прийму, сделай пожалуйста вместе со следующим заднием.

2021-12-13 13:23 UTC, dean992008 approved these changes

2021-12-13 13:23 UTC, merged